# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
            AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      in_memory:
        memory: ~
      our_db_provider:
                  entity:
                      class: AppBundle:User
                      property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
              login_path: login
              check_path: login
              success_handler: redirect.after.login

            logout:
              path: /logout
              target: /
              success_handler: redirect.after.logout

            pattern: ^/
            http_basic: ~
            provider: our_db_provider

            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
