# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  redirect.after.login:
    class: AppBundle\Handler\AuthenticationSuccessHandler
    arguments: ["@router", "@security.authorization_checker"]

  redirect.after.logout:
    class: AppBundle\Handler\LogoutSuccessHandler
    arguments: ["@router"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
